import './Home.css'; 
import Header from '../component/Header.js'; 

export default function Home() {
    return (
        <div className="home-page">
            <Header /> 
            
            {/* 1. Hero Section - يعبر عن توليد الأكواد والهياكل */}
            <section className="hero-section">
                <div className="hero-glowing-blur"></div> 
                <div className="container hero-container">
                    <span className="hero-badge">AI-Powered Architecture Engine</span>
                    <h1 className="hero-title">
                        From Idea to Architecture <span className="gradient-text">in Seconds</span>
                    </h1>
                    <p className="hero-subtitle">
                        ProLink translates your product requirements into actionable tasks, complete file structures, and production-ready database schemas instantly.
                    </p>
                    <div className="hero-actions">
                        <a href="#Architecture-Engine" className="btn-primary">Start Building Free</a>
                        <a href="#how-it-works" className="btn-secondary">See How It Works</a>
                    </div>
                </div>
            </section>

            {/* 2. How It Works Section - يشرح بدقة كيف تتحول الفكرة لملفات وأكواد */}
            <section id="how-it-works" className="section how-it-works-section">
                <div className="container">
                    <div className="section-header">
                        <h2 className="section-title">The Generation Pipeline</h2>
                        <p className="section-desc">From abstract thoughts to structured, deployable core architecture in 3 phases.</p>
                    </div>
                    <div className="steps-grid">
                        <div className="step-card">
                            <div className="step-number">01</div>
                            <h3>Requirement Breakdown</h3>
                            <p>Input your text specs. Our engine extracts business logic and maps out an agile roadmap of development tasks.</p>
                        </div>
                        <div className="step-card">
                            <div className="step-number">02</div>
                            <h3>File Tree Schematics</h3>
                            <p>The platform architect builds a complete directory layout, tailored precisely to your technology stack standards.</p>
                        </div>
                        <div className="step-card">
                            <div className="step-number">03</div>
                            <h3>Schema & Code Synthesis</h3>
                            <p>Get instant production-ready Prisma/SQL schemas and structural boilerplates to start coding immediately.</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* 3. Showcase Section - يستعرض نماذج حقيقية تم توليدها بواسطة موقعك */}
            <section id="Showcase" className="section showcase-section">
                <div className="container">
                    <div className="section-header">
                        <h2 className="section-title">Engine Blueprints</h2>
                        <p className="section-desc">Explore ready-to-use architecture models engineered and generated by ProLink.</p>
                    </div>
                    <div className="showcase-grid">
                        <div className="project-card">
                            <div className="project-image-wrapper">
                                <div className="project-placeholder code-preview">
                                    <code>{`model User {\n  id    String @id\n  tasks Task[]\n}`}</code>
                                </div>
                            </div>
                            <div className="project-info">
                                <span>SaaS Platform Boilerplate</span>
                                <h3>Multi-Tenant Architecture</h3>
                            </div>
                        </div>
                        <div className="project-card">
                            <div className="project-image-wrapper">
                                <div className="project-placeholder code-preview">
                                    <code>{`├── api/\n├── controllers/\n└── prisma/`}</code>
                                </div>
                            </div>
                            <div className="project-info">
                                <span>RESTful API Stack</span>
                                <h3>Express & Prisma Workspace</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* 4. Core Features Section - يستعرض قدرات المحرك الهندسي للموقع */}
            <section id="Services" className="section services-section">
                <div className="container">
                    <div className="section-header">
                        <h2 className="section-title">Core Capabilities</h2>
                        <p className="section-desc">An advanced engineering toolkit designed to skip configuration and start building.</p>
                    </div>
                    <div className="services-grid">
                        <div className="service-card">
                            <div className="service-icon">⚡</div>
                            <h3>Automated Task Roadmaps</h3>
                            <p>Translates complex system requirements into modular, checklist-ready dev tasks to accelerate your sprint planning.</p>
                        </div>
                        <div className="service-card">
                            <div className="service-icon">📁</div>
                            <h3>Dynamic File Tree Mapping</h3>
                            <p>Generates standardized repository blueprints so your team maintains bulletproof project cleanliness across folders.</p>
                        </div>
                        <div className="service-card">
                            <div className="service-icon">🛠️</div>
                            <h3>Schema & Code Generation</h3>
                            <p>Creates clean database models, relation matrices, and routing logic without writing a single line of boilerplate manually.</p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    );
}